### ISSUE TITLE
GPU mode interfering with PyTorch CUDA objects

### ISSUE THREAD

**Issue by bamos** [bodono/scs-python#10]
I'm trying to use the GPU mode (`gpu=True`) as part of a larger PyTorch 1.0.1 program. Calling into SCS interferes with PyTorch CUDA objects. Here's a MWE:

```python
#!/usr/bin/env python3

import scs
import numpy as np
import scipy.sparse as sp
import torch

c = np.array([-1.])
b = np.array([1., -0.])
A = sp.csc_matrix([1., -1.]).T.tocsc()
data = {'A': A, 'b': b, 'c': c}
cone = {'q': [], 'l': 2}

# First solve here works.
sol = scs.solve(data, cone, gpu=False, verbose=False)

# Create a PyTorch GPU tensor.
x = torch.randn(4).cuda()
print(x)

# Call into SCS again.
sol = scs.solve(data, cone, gpu=True, verbose=False)

# Trying to access `x` again fails.
print(x)
```

## Output

```
$ ./t.py
tensor([-1.7090,  0.2887, -0.2694,  0.3425], device='cuda:0')
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1549630534704/work/aten/src/THC/generated/../THCReduceAll.cuh line=317 error=11 : invalid argument
Traceback (most recent call last):
  File "./t.py", line 20, in <module>
    print(x)
  File "/nethome/bamos/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 66, in __repr__
    return torch._tensor_str._str(self)
  File "/nethome/bamos/anaconda3/lib/python3.6/site-packages/torch/_tensor_str.py", line 277, in _str
    tensor_str = _tensor_str(self, indent)
  File "/nethome/bamos/anaconda3/lib/python3.6/site-packages/torch/_tensor_str.py", line 195, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/nethome/bamos/anaconda3/lib/python3.6/site-packages/torch/_tensor_str.py", line 84, in __init__
    nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
RuntimeError: cuda runtime error (11) : invalid argument at /opt/conda/conda-bld/pytorch_1549630534704/work/aten/src/THC/generated/../THCReduceAll.cuh:317
```

**Comment by bamos** [comment]
I found the cause of this. It's from the `cudaDeviceReset` call in `free_lin_sys_work`: https://github.com/cvxgrp/scs/blob/master/linsys/gpu/private.c#L169

Commenting out that line fixes my MWE so as a hacky workaround for my other code I currently have this disabled. As a proper fix, perhaps an SCS option could be added to disable this line?

**Comment by bodono** [comment]
Presumably that can just be removed, it was probably overkill to put that in in the first place.

**Comment by bamos** [comment]
Fixed
